routes/web.php
<?php

//Route::get('/{any}', 'SinglePageController@index')->where('any', '.*');


Route::get('/', 'HomeController');
Route::get('home', 'HomeController');

Route::name('admin.')
	->prefix('admin')
	->middleware('auth')
	->group(function () {
		// Notifications
		Route::post('notify/read', 'NotificationController@markAsRead')
			->name('markAsRead');
		Route::post('notify/read/{id}', 'NotificationController@markAsReadById')
			->name('markAsReadById');
		Route::get('notify/list/unread', 'NotificationController@listAllUnReadNotifications')
			->name('listUnreadNotifications');
		Route::get('notify/list/read', 'NotificationController@listAllReadNotifications')
			->name('listReadNotifications');
		Route::get('notify/{id}/list', 'NotificationController@listAllNotifications')
			->name('listAllNotifications');
		Route::post('notify/{id}/remove', 'NotificationController@removeNotificationById');
	});

/*Route::middleware('auth')->get('logout', function() {

})->name('logout');*/

Route::get('logout', 'Auth\LogoutController')->middleware('auth');

Auth::routes(['verify' => true]);

Route::name('js.')->group(function () {
	Route::get('dynamic', 'JsController@dynamic')->name('dynamic');
});

// Get authenticated user
/*Route::get('users / auth', function() {
    return response()->json(['user' => Auth::check() ? Auth::user() : false]);
});*/


// Test Auth via VK
Route::get('login /{
		provider}', 'LoginController@redirectToProvider')
	->name('socialLogin');
Route::get('login/{provider}/callback', 'LoginController@handleProviderCallback')
	->name('socialLoginCallback');


Route::get('test/delivery/cdek/oauth', 'TestDeliveryController@cdekAuth');
Route::get('test/delivery/cdek/get/cities', 'TestDeliveryController@getListCities');
Route::get('test/delivery/cdek/get/regions', 'TestDeliveryController@getListRegions');
Route::get('test/delivery/cdek/get/delivery-points', 'TestDeliveryController@getListDeliveryPoints');
Route::get('test/delivery/cdek/get/reg-order', 'TestDeliveryController@regOrder');

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>@yield('title', 'Stisla Laravel') &mdash; {{ env('APP_NAME') }}</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- General CSS Files -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <!-- Template CSS -->
    <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/components.css')}}">
    <!-- CSS Libraries -->
    @yield('plugin_css')
</head>
<body>
<div id="app"></div>

<script src="{{ route('js.dynamic') }}"></script>
<script src="{{ asset('js/edit.js') }}?{{ uniqid() }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
<script src="{{ asset('assets/js/stisla.js') }}"></script>
<script src="{{ asset('assets/js/scripts.js') }}"></script>
</body>
</html>